server:
  port: 9002
spring:
  application:
    name: teacher
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloudtest?characterEncoding=UTF8
    #修改成自己的帐号密码
    username: root
    password: lzy1998121
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9010/eureka/ #注意要与服务中心配置的url一致
  instance:
    prefer-ip-address: true #跨域访问
#开启熔断器
feign:
  hystrix:
    enabled: true
